### ISSUE TITLE
<version>2.0.2</version> ,mockito NoSuchMethodError

### ISSUE THREAD

**Issue by zuwensong** [powermock/powermock#988]
java8;
powermock-api-mockito2, version:2.0.2
build error:
![image](https://user-images.githubusercontent.com/18671875/57767255-7880e600-773b-11e9-8cab-3c6cfc2c38ed.png)
![image](https://user-images.githubusercontent.com/18671875/57767274-86366b80-773b-11e9-8d13-31601094d372.png)

version less than 2.0.2 is nomal.

**Comment by Tibor17** [comment]
@zuwensong 
hm, what method?
I am using it without any issue.

**Comment by zuwensong** [comment]
![image](https://user-images.githubusercontent.com/18671875/57825625-3f478500-77d2-11e9-834e-2e382afd4e95.png)
![image](https://user-images.githubusercontent.com/18671875/57825672-6ef68d00-77d2-11e9-81ad-0a0a55be3b48.png)

**Comment by Danc2050** [comment]
I was able to get this to work using the following for `2.0.7` (in Gradle):

```
    testCompile 'junit:junit:4.12',
            'org.powermock:powermock-core:2.0.7',
            'org.powermock:powermock-module-junit4:2.0.7'
            'org.powermock:powermock-api-mockito2:2.0.7'
```
Perhaps you were missing the `'org.powermock:powermock-core:2.0.x
'`?
